baseURL: "https://natashakatson.com/"
title: Natasha's Journey
paginate: 5
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

googleAnalytics: UA-186434079-1
disqusShortname: natashakatson-github-io

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives/
                  weight: 5
                - name: Tags
                  url: tags/
                  weight: 10
    ru:
        languageName: "Russian"
        weight: 2
        homeInfoParams:
          Title: "Natasha's Journey"
          Content: >
            Мой персональный блог.

            Здесь я постараюсь рассказывать разные не очень типичные истории про иммиграцию, местные цены, работу, ну и другое, что меня окружает.

        license: "CC BY-NC-ND 4.0"
        licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/deed.ru"
        menu:
            main:
                - name: Архив
                  url: archives/
                  weight: 5
                - name: Тэги
                  url: tags/
                  weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: ""
    author: Natasha Katson
    license: "CC BY-NC-ND 4.0"
    licenseUrl: "https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en"
    ShowReadingTime: true
    comments: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    homeInfoParams:
        Title: "Natasha's Journey"
        Content: >
            Welcome to my personal blog.

            Here I want cover some untypical (or not) stories about immigration, exploring the world, prices, work and much more.

    socialIcons:
        - name: twitter
          url: "https://twitter.com/natashakatson"
        - name: facebook
          url: "https://www.facebook.com/natasha.katson"
        - name: linkedin
          url: "https://www.linkedin.com/in/natashakatson/"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true